# Composite action to download and install the space binary from build artifacts.
# Used by modes-reusable.yaml to set up the custom space binary for testing.
#
# This action handles:
# - Downloading the correct binary for the current OS (Linux or macOS)
# - Renaming and installing it to a known location
# - Providing the NSC_POWERTOYS_DIR value for the cache action
#
# Usage:
#   - name: Setup space binary
#     id: space
#     uses: ./.github/actions/setup-space-binary
#     with:
#       space-source-ref: ${{ inputs.space-source-ref }}
#
#   - name: Setup cache
#     uses: ./
#     with:
#       mode: apt
#     env:
#       NSC_POWERTOYS_DIR: ${{ steps.space.outputs.powertoys-dir }}

name: 'Setup Space Binary'
description: 'Downloads and installs the space binary from build artifacts'

inputs:
  space-source-ref:
    description: 'Git ref of space (if empty, no binary is downloaded)'
    required: false
    default: ''

outputs:
  powertoys-dir:
    description: 'Value for NSC_POWERTOYS_DIR env var (empty if no custom binary)'
    value: ${{ steps.set-output.outputs.powertoys-dir }}

runs:
  using: 'composite'
  steps:
    - name: Download space binary
      if: inputs.space-source-ref != ''
      uses: actions/download-artifact@v4
      with:
        name: space-${{ runner.os == 'macOS' && 'macos' || 'linux' }}
        path: ${{ runner.temp }}/space-bin

    - name: Install space binary
      if: inputs.space-source-ref != ''
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          mv "${{ runner.temp }}/space-bin/space-linux-amd64" "${{ runner.temp }}/space-bin/space"
        else
          mv "${{ runner.temp }}/space-bin/space-darwin-arm64" "${{ runner.temp }}/space-bin/space"
        fi
        chmod +x "${{ runner.temp }}/space-bin/space"

    - name: Set output
      id: set-output
      shell: bash
      run: |
        if [ -n "${{ inputs.space-source-ref }}" ]; then
          echo "powertoys-dir=${{ runner.temp }}/space-bin/" >> $GITHUB_OUTPUT
        else
          echo "powertoys-dir=" >> $GITHUB_OUTPUT
        fi
