name: Test Homebrew caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

  # Allow check to run on the merge queue so that it is eligible to be a "required" check.
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [namespace-profile-macos, namespace-profile-e2e-small]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Homebrew cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: brew

      - run: |
          brew --version
          brew install hello
          which hello

      - if: runner.os == 'macOS'
        # Not available on Linux.
        run: brew tap vectordotdev/brew && brew install vector
