name: Prints errors

on:
  workflow_dispatch:

jobs:
  with-labels:
    name: Labels do not configure cache volume
    runs-on: nscloud-ubuntu-22.04-amd64-2x4

    steps:
      - name: Github Checkout current
        uses: actions/checkout@v5

      - name: Setup Go cache
        continue-on-error: true
        uses: ./ # Uses an action in the root directory
        with:
          cache: go

  with-profile:
    name: Profile does not configure cache volume
    runs-on: namespace-profile-default

    steps:
      - name: Github Checkout current
        uses: actions/checkout@v5

      - name: Setup Go cache
        continue-on-error: true
        uses: ./ # Uses an action in the root directory
        with:
          cache: go
